const { helper_pick, helper_range } = require('./generate-data.js');

const imgBase = 'https://placehold.co/600x600';

function imgs(id, count) {
  const a = [];
  for (let i = 1; i <= count; i++) a.push(imgBase + '?text=' + encodeURIComponent(id) + '-img' + i);
  return a;
}

const productsA = [
  // === ELECTRONICS (12) ===
  { id: "E001", name: "Wireless Bluetooth Earbuds Pro", brand: "SoundMax", category: "electronics", price: 1299, originalPrice: 2499, rating: 4.5, description: "True wireless earbuds with active noise cancellation, 30hr battery life, and IPX5 water resistance.", colors: ["Black", "White", "Blue"], sizes: [], inStock: true, images: imgs("E001", 4) },
  { id: "E002", name: "4K Ultra HD Smart TV 55\"", brand: "VisionTech", category: "electronics", price: 34999, originalPrice: 54999, rating: 4.6, description: "55-inch QLED Smart TV with Dolby Vision, 120Hz refresh rate, and built-in streaming apps.", colors: ["Black"], sizes: ["55 inch", "65 inch"], inStock: true, images: imgs("E002", 3) },
  { id: "E003", name: "Power Bank 20000mAh", brand: "ChargeUp", category: "electronics", price: 1599, originalPrice: 2999, rating: 4.3, description: "High-capacity power bank with dual USB ports, quick charge 3.0, and LED display.", colors: ["Black", "Blue"], sizes: [], inStock: true, images: imgs("E003", 3) },
  { id: "E004", name: "Portable Bluetooth Speaker", brand: "BoomBox", category: "electronics", price: 2499, originalPrice: 4499, rating: 4.4, description: "360-degree sound speaker with deep bass, waterproof IPX7, and 12-hour battery.", colors: ["Red", "Black", "Blue", "Green"], sizes: [], inStock: true, images: imgs("E004", 4) },
  { id: "E005", name: "Wireless Charging Pad", brand: "ChargeUp", category: "electronics", price: 799, originalPrice: 1499, rating: 4.2, description: "Fast wireless charging pad compatible with all Qi-enabled devices. Anti-slip design.", colors: ["Black", "White"], sizes: [], inStock: true, images: imgs("E005", 3) },
  { id: "E006", name: "USB-C Hub 7-in-1", brand: "TechLink", category: "electronics", price: 1999, originalPrice: 3499, rating: 4.3, description: "Multiport adapter with HDMI, USB-A x3, SD card reader, and 100W PD charging.", colors: ["Space Grey", "Silver"], sizes: [], inStock: true, images: imgs("E006", 3) },
  { id: "E007", name: "Smart Plug WiFi", brand: "HomeConnect", category: "electronics", price: 599, originalPrice: 1299, rating: 4.1, description: "Control your appliances remotely via app. Works with Alexa and Google Assistant.", colors: ["White"], sizes: [], inStock: true, images: imgs("E007", 3) },
  { id: "E008", name: "Webcam HD 1080p", brand: "ClearView", category: "electronics", price: 2299, originalPrice: 3999, rating: 4.2, description: "Full HD webcam with auto-focus, noise-cancelling mic, and wide-angle lens.", colors: ["Black"], sizes: [], inStock: true, images: imgs("E008", 3) },
  { id: "E009", name: "Streaming Media Player", brand: "StreamTech", category: "electronics", price: 3999, originalPrice: 5999, rating: 4.5, description: "4K streaming device with voice remote, Dolby Atmos support, and 32GB storage.", colors: ["Black"], sizes: ["16GB", "32GB"], inStock: true, images: imgs("E009", 3) },
  { id: "E010", name: "LED Desk Lamp", brand: "BrightLight", category: "electronics", price: 1499, originalPrice: 2499, rating: 4.4, description: "Dimmable LED lamp with 5 color modes, USB charging port, and touch control.", colors: ["Black", "White", "Silver"], sizes: [], inStock: true, images: imgs("E010", 4) },
  { id: "E011", name: "Digital Photo Frame", brand: "FrameIt", category: "electronics", price: 4999, originalPrice: 7999, rating: 4.3, description: "10.1-inch WiFi digital frame with auto-rotate, motion sensor, and cloud sharing.", colors: ["Black", "White"], sizes: [], inStock: true, images: imgs("E011", 3) },
  { id: "E012", name: "Surge Protector 6-Outlet", brand: "PowerGuard", category: "electronics", price: 899, originalPrice: 1599, rating: 4.1, description: "6-outlet surge protector with 2 USB ports and 1000-joule energy rating.", colors: ["White"], sizes: [], inStock: true, images: imgs("E012", 3) },

  // === CLOTHING (8) ===
  { id: "C001", name: "Classic Oxford Shirt", brand: "UrbanStyle", category: "clothing", price: 999, originalPrice: 1999, rating: 4.3, description: "Premium cotton oxford shirt with a relaxed fit. Perfect for casual and semi-formal occasions.", colors: ["White", "Blue", "Pink"], sizes: ["S", "M", "L", "XL"], inStock: true, images: imgs("C001", 4) },
  { id: "C002", name: "Slim Fit Chinos", brand: "UrbanStyle", category: "clothing", price: 1299, originalPrice: 2499, rating: 4.4, description: "Stretch cotton chinos with a modern slim fit. Features a comfortable waistband.", colors: ["Khaki", "Navy", "Olive"], sizes: ["28", "30", "32", "34", "36"], inStock: true, images: imgs("C002", 3) },
  { id: "C003", name: "Crew Neck T-Shirt Pack", brand: "BasicWear", category: "clothing", price: 699, originalPrice: 1299, rating: 4.2, description: "Pack of 3 breathable cotton t-shirts. Pre-shrunk and fade-resistant.", colors: ["Black", "White", "Grey"], sizes: ["S", "M", "L", "XL"], inStock: true, images: imgs("C003", 3) },
  { id: "C004", name: "Denim Jacket", brand: "RetroFit", category: "clothing", price: 2499, originalPrice: 4499, rating: 4.5, description: "Classic denim jacket with button closure, chest pockets, and adjustable waist tabs.", colors: ["Blue", "Black"], sizes: ["S", "M", "L", "XL"], inStock: true, images: imgs("C004", 4) },
  { id: "C005", name: "Formal Blazer", brand: "PrimeOccasion", category: "clothing", price: 3999, originalPrice: 7999, rating: 4.6, description: "Tailored two-button blazer in premium fabric. Fully lined interior.", colors: ["Black", "Navy", "Charcoal"], sizes: ["S", "M", "L", "XL"], inStock: true, images: imgs("C005", 3) },
  { id: "C006", name: "Polo T-Shirt", brand: "Sportive", category: "clothing", price: 799, originalPrice: 1599, rating: 4.3, description: "Performance polo with moisture-wicking fabric and anti-odor technology.", colors: ["Red", "Blue", "Green", "White"], sizes: ["S", "M", "L", "XL"], inStock: true, images: imgs("C006", 3) },
  { id: "C007", name: "Jogger Pants", brand: "ActiveEdge", category: "clothing", price: 1199, originalPrice: 2199, rating: 4.4, description: "Tapered jogger pants with elastic cuffs, zip pockets, and drawstring waist.", colors: ["Black", "Grey", "Navy"], sizes: ["S", "M", "L", "XL"], inStock: true, images: imgs("C007", 4) },
  { id: "C008", name: "Winter Hoodie", brand: "CozyFit", category: "clothing", price: 1799, originalPrice: 3299, rating: 4.5, description: "Fleece-lined hoodie with kangaroo pocket, adjustable hood, and ribbed cuffs.", colors: ["Black", "Grey", "Maroon", "Navy"], sizes: ["S", "M", "L", "XL"], inStock: true, images: imgs("C008", 3) },

  // === HOME & KITCHEN (10) ===
  { id: "HK001", name: "Non-Stick Cookware Set", brand: "ChefMate", category: "home-kitchen", price: 2999, originalPrice: 5999, rating: 4.5, description: "10-piece non-stick cookware set with tempered glass lids and heat-resistant handles.", colors: ["Black", "Red"], sizes: ["10 Piece"], inStock: true, images: imgs("HK001", 4) },
  { id: "HK002", name: "Robot Vacuum Cleaner", brand: "CleanBot", category: "home-kitchen", price: 14999, originalPrice: 29999, rating: 4.6, description: "Smart robot vacuum with LiDAR navigation, app control, and auto-empty dock.", colors: ["White", "Black"], sizes: [], inStock: true, images: imgs("HK002", 3) },
  { id: "HK003", name: "Air Purifier HEPA", brand: "PureAir", category: "home-kitchen", price: 8999, originalPrice: 14999, rating: 4.4, description: "True HEPA H13 air purifier covering up to 500 sq ft. Quiet operation mode.", colors: ["White", "Grey"], sizes: ["Small", "Medium", "Large"], inStock: true, images: imgs("HK003", 3) },
  { id: "HK004", name: "Electric Kettle 1.7L", brand: "BoilQuick", category: "home-kitchen", price: 1299, originalPrice: 2499, rating: 4.3, description: "BPA-free electric kettle with auto shut-off, boil-dry protection, and boil indicator.", colors: ["Silver", "Black", "Red"], sizes: [], inStock: true, images: imgs("HK004", 3) },
  { id: "HK005", name: "Stainless Steel Water Bottle", brand: "HydroFlask", category: "home-kitchen", price: 899, originalPrice: 1799, rating: 4.5, description: "Double-wall vacuum insulated bottle. Keeps drinks cold 24hrs or hot 12hrs.", colors: ["Silver", "Black", "Blue", "Pink"], sizes: ["500ml", "750ml", "1L"], inStock: true, images: imgs("HK005", 4) },
  { id: "HK006", name: "Memory Foam Pillow", brand: "DreamWell", category: "home-kitchen", price: 1999, originalPrice: 3999, rating: 4.6, description: "Ergonomic memory foam pillow with cooling gel layer and hypoallergenic cover.", colors: ["White"], sizes: ["Standard", "Queen", "King"], inStock: true, images: imgs("HK006", 3) },
  { id: "HK007", name: "Bamboo Cutting Board Set", brand: "GreenChef", category: "home-kitchen", price: 799, originalPrice: 1499, rating: 4.2, description: "Set of 3 bamboo cutting boards with juice grooves and easy-grip handles.", colors: ["Natural"], sizes: ["Small", "Medium", "Large"], inStock: true, images: imgs("HK007", 3) },
  { id: "HK008", name: "Bed Sheet Set - 400TC", brand: "LuxLinens", category: "home-kitchen", price: 1499, originalPrice: 2999, rating: 4.5, description: "400-thread count cotton bed sheet set with deep pocket fitted sheet.", colors: ["White", "Grey", "Blue", "Beige"], sizes: ["Single", "Double", "Queen", "King"], inStock: true, images: imgs("HK008", 4) },
  { id: "HK009", name: "Essential Oil Diffuser", brand: "AromaMist", category: "home-kitchen", price: 1299, originalPrice: 2499, rating: 4.4, description: "Ultrasonic diffuser with 7 LED colors, auto shut-off, and whisper-quiet operation.", colors: ["White", "Wood Grain"], sizes: ["300ml", "500ml"], inStock: true, images: imgs("HK009", 3) },
  { id: "HK010", name: "Stainless Steel Trash Can", brand: "CleanHome", category: "home-kitchen", price: 2499, originalPrice: 4499, rating: 4.3, description: "50L touchless sensor trash can with soft-close lid and fingerprint-resistant finish.", colors: ["Silver", "Black"], sizes: ["30L", "50L"], inStock: true, images: imgs("HK010", 3) },

  // === BOOKS (8) ===
  { id: "B001", name: "Atomic Habits", brand: "Penguin", category: "books", price: 399, originalPrice: 699, rating: 4.7, description: "An easy and proven way to build good habits and break bad ones by James Clear.", colors: [], sizes: ["Paperback", "Hardcover"], inStock: true, images: imgs("B001", 3) },
  { id: "B002", name: "The Psychology of Money", brand: "Pan Macmillan", category: "books", price: 349, originalPrice: 599, rating: 4.6, description: "Timeless lessons on wealth, greed, and happiness by Morgan Housel.", colors: [], sizes: ["Paperback"], inStock: true, images: imgs("B002", 3) },
  { id: "B003", name: "Sapiens: A Brief History", brand: "Harper", category: "books", price: 499, originalPrice: 899, rating: 4.8, description: "A sweeping narrative of humankind's creation and evolution by Yuval Noah Harari.", colors: [], sizes: ["Paperback", "Hardcover", "Kindle"], inStock: true, images: imgs("B003", 4) },
  { id: "B004", name: "Rich Dad Poor Dad", brand: "Plata Publishing", category: "books", price: 299, originalPrice: 549, rating: 4.5, description: "What the rich teach their kids about money by Robert Kiyosaki.", colors: [], sizes: ["Paperback"], inStock: true, images: imgs("B004", 3) },
  { id: "B005", name: "The Alchemist", brand: "Harper", category: "books", price: 299, originalPrice: 499, rating: 4.6, description: "A magical fable about following your dreams by Paulo Coelho.", colors: [], sizes: ["Paperback", "Hardcover"], inStock: true, images: imgs("B005", 3) },
  { id: "B006", name: "Thinking, Fast and Slow", brand: "Penguin", category: "books", price: 449, originalPrice: 799, rating: 4.5, description: "A groundbreaking tour of the mind by Daniel Kahneman.", colors: [], sizes: ["Paperback"], inStock: true, images: imgs("B006", 3) },
  { id: "B007", name: "The Subtle Art of Not Giving", brand: "Harper", category: "books", price: 399, originalPrice: 699, rating: 4.4, description: "A counterintuitive approach to living a good life by Mark Manson.", colors: [], sizes: ["Paperback", "Kindle"], inStock: true, images: imgs("B007", 3) },
  { id: "B008", name: "Zero to One", brand: "Penguin", category: "books", price: 399, originalPrice: 699, rating: 4.6, description: "Notes on startups, or how to build the future by Peter Thiel.", colors: [], sizes: ["Paperback", "Hardcover"], inStock: true, images: imgs("B008", 3) },

  // === SPORTS (8) ===
  { id: "S001", name: "Yoga Mat Premium", brand: "ZenFit", category: "sports", price: 999, originalPrice: 1999, rating: 4.5, description: "6mm thick non-slip yoga mat with alignment lines and carrying strap.", colors: ["Purple", "Blue", "Green", "Pink"], sizes: ["6mm", "8mm"], inStock: true, images: imgs("S001", 4) },
  { id: "S002", name: "Resistance Bands Set", brand: "FlexPower", category: "sports", price: 799, originalPrice: 1499, rating: 4.3, description: "Set of 5 resistance bands with different intensities. Includes door anchor and bag.", colors: ["Multi"], sizes: ["Light", "Medium", "Heavy"], inStock: true, images: imgs("S002", 3) },
  { id: "S003", name: "Jump Rope Speed", brand: "SkipPro", category: "sports", price: 399, originalPrice: 799, rating: 4.2, description: "Adjustable speed jump rope with ball bearings and memory foam handles.", colors: ["Black", "Blue", "Red"], sizes: [], inStock: true, images: imgs("S003", 3) },
  { id: "S004", name: "Running Armband", brand: "RunTech", category: "sports", price: 499, originalPrice: 999, rating: 4.1, description: "Waterproof running armband with key pocket, fits phones up to 6.7 inches.", colors: ["Black", "Pink"], sizes: ["S/M", "L/XL"], inStock: true, images: imgs("S004", 3) },
  { id: "S005", name: "Foam Roller", brand: "MuscleRelief", category: "sports", price: 699, originalPrice: 1299, rating: 4.4, description: "High-density foam roller for muscle recovery and deep tissue massage.", colors: ["Black", "Blue", "Purple"], sizes: ["12 inch", "18 inch"], inStock: true, images: imgs("S005", 3) },
  { id: "S006", name: "Water Bottle Sport 1L", brand: "HydroActive", category: "sports", price: 499, originalPrice: 999, rating: 4.3, description: "BPA-free sport bottle with flip-top lid and integrated carry loop.", colors: ["Blue", "Green", "Pink", "Black"], sizes: ["750ml", "1L"], inStock: true, images: imgs("S006", 4) },
  { id: "S007", name: "Gym Gloves", brand: "GripMaster", category: "sports", price: 599, originalPrice: 1099, rating: 4.2, description: "Padded gym gloves with wrist support and breathable mesh back.", colors: ["Black", "Red", "Blue"], sizes: ["S", "M", "L", "XL"], inStock: true, images: imgs("S007", 3) },
  { id: "S008", name: "Swimming Goggles", brand: "AquaVision", category: "sports", price: 449, originalPrice: 899, rating: 4.3, description: "Anti-fog swimming goggles with UV protection and adjustable silicone strap.", colors: ["Blue", "Black", "Clear"], sizes: [], inStock: true, images: imgs("S008", 3) }
];

module.exports = productsA;
