const { helper_pick, helper_range } = require('./generate-data.js');

const imgBase = 'https://placehold.co/600x600';
function imgs(id, count) {
  const a = [];
  for (let i = 1; i <= count; i++) a.push(imgBase + '?text=' + encodeURIComponent(id) + '-img' + i);
  return a;
}

const productsC = [
  // === GAMING (8) ===
  { id: "GM001", name: "Gaming Mouse RGB", brand: "PrecisionTech", category: "gaming", price: 1299, originalPrice: 2499, rating: 4.5, description: "16000 DPI gaming mouse with RGB lighting, 8 programmable buttons, and braided cable.", colors: ["Black", "White"], sizes: [], inStock: true, images: imgs("GM001", 4) },
  { id: "GM002", name: "Mechanical Keyboard RGB", brand: "KeyStrike", category: "gaming", price: 3999, originalPrice: 7499, rating: 4.6, description: "Full-size mechanical keyboard with Cherry MX switches, per-key RGB, and aluminum frame.", colors: ["Black", "White"], sizes: [], inStock: true, images: imgs("GM002", 3) },
  { id: "GM003", name: "Gaming Headset 7.1", brand: "AudioStrike", category: "gaming", price: 2499, originalPrice: 4999, rating: 4.4, description: "7.1 surround sound gaming headset with detachable mic, memory foam cushions.", colors: ["Black", "Red", "Blue"], sizes: [], inStock: true, images: imgs("GM003", 3) },
  { id: "GM004", name: "Gaming Chair Racing", brand: "ThroneGaming", category: "gaming", price: 12999, originalPrice: 24999, rating: 4.5, description: "Ergonomic gaming chair with lumbar support, recline to 180 degrees, and armrests.", colors: ["Black/Red", "Black/Blue", "All Black"], sizes: [], inStock: true, images: imgs("GM004", 4) },
  { id: "GM005", name: "Controller PS5", brand: "PlayGear", category: "gaming", price: 4999, originalPrice: 6999, rating: 4.7, description: "Wireless controller with haptic feedback, adaptive triggers, and built-in mic.", colors: ["White", "Black", "Blue"], sizes: [], inStock: true, images: imgs("GM005", 3) },
  { id: "GM006", name: "Gaming Desk Large", brand: "GameStation", category: "gaming", price: 7999, originalPrice: 14999, rating: 4.4, description: "60-inch gaming desk with cable management, cup holder, and headphone hook.", colors: ["Black", "Carbon Fiber"], sizes: ["48 inch", "60 inch"], inStock: true, images: imgs("GM006", 3) },
  { id: "GM007", name: "Game Controller Joystick", brand: "RetroPlay", category: "gaming", price: 1999, originalPrice: 3999, rating: 4.3, description: "Arcade-style fight stick with Sanwa buttons and removable USB cable.", colors: ["Black", "Red"], sizes: [], inStock: true, images: imgs("GM007", 3) },
  { id: "GM008", name: "Gaming Mousepad XL", brand: "SmoothEdge", category: "gaming", price: 599, originalPrice: 1199, rating: 4.3, description: "Extended gaming mousepad with stitched edges, non-slip base, and micro-texture surface.", colors: ["Black", "Black/Red", "Space"], sizes: ["XL", "XXL"], inStock: true, images: imgs("GM008", 3) },

  // === FURNITURE (7) ===
  { id: "FR001", name: "Modular Sofa 3-Seater", brand: "ComfortPlus", category: "furniture", price: 19999, originalPrice: 39999, rating: 4.6, description: "Fabric modular sofa with reversible chaise, solid wood frame, and high-density foam.", colors: ["Grey", "Blue", "Beige"], sizes: ["2 Seater", "3 Seater"], inStock: true, images: imgs("FR001", 4) },
  { id: "FR002", name: "Coffee Table Oak", brand: "WoodCraft", category: "furniture", price: 5999, originalPrice: 10999, rating: 4.4, description: "Solid oak coffee table with lower shelf and tapered legs. Scandinavian design.", colors: ["Natural Oak", "Walnut"], sizes: [], inStock: true, images: imgs("FR002", 3) },
  { id: "FR003", name: "Bookshelf 5-Tier", brand: "SpaceMaker", category: "furniture", price: 4999, originalPrice: 8999, rating: 4.3, description: "Industrial-style bookshelf with metal frame and 5 wooden tiers.", colors: ["Black/Brown", "Black/Natural"], sizes: [], inStock: true, images: imgs("FR003", 3) },
  { id: "FR004", name: "Dining Table 6-Seater", brand: "DineElegant", category: "furniture", price: 14999, originalPrice: 27999, rating: 4.5, description: "Solid wood dining table with 6 chairs. Mid-century modern design.", colors: ["Walnut", "White Oak"], sizes: ["4 Seater", "6 Seater"], inStock: true, images: imgs("FR004", 4) },
  { id: "FR005", name: "Nightstand 2-Drawer", brand: "SleepZone", category: "furniture", price: 3499, originalPrice: 6499, rating: 4.3, description: "Bedside table with 2 drawers, USB charging port, and soft-close mechanism.", colors: ["White", "Grey", "Walnut"], sizes: [], inStock: true, images: imgs("FR005", 3) },
  { id: "FR006", name: "Office Desk L-Shape", brand: "WorkZone", category: "furniture", price: 8999, originalPrice: 16999, rating: 4.4, description: "L-shaped executive desk with 2 cable grommets, monitor stand, and keyboard tray.", colors: ["White", "Walnut", "Black"], sizes: [], inStock: true, images: imgs("FR006", 3) },
  { id: "FR007", name: "Wardrobe Sliding Door", brand: "ClosetPro", category: "furniture", price: 12999, originalPrice: 24999, rating: 4.5, description: "3-door wardrobe with mirror, adjustable shelves, and hanging rod.", colors: ["White", "Oak"], sizes: ["3 Door", "4 Door"], inStock: true, images: imgs("FR007", 3) },

  // === CAMERAS (7) ===
  { id: "CM001", name: "Mirrorless Camera Kit", brand: "SnapPro", category: "cameras", price: 44999, originalPrice: 74999, rating: 4.7, description: "26MP mirrorless camera with 18-55mm kit lens, in-body stabilization, and 4K video.", colors: ["Black", "Silver"], sizes: [], inStock: true, images: imgs("CM001", 4) },
  { id: "CM002", name: "Action Camera 4K", brand: "AdventureCam", category: "cameras", price: 3999, originalPrice: 7499, rating: 4.4, description: "4K action camera with waterproof case, EIS, and WiFi connectivity.", colors: ["Black", "Blue"], sizes: [], inStock: true, images: imgs("CM002", 3) },
  { id: "CM003", name: "Tripod Carbon Fiber", brand: "StableShot", category: "cameras", price: 4999, originalPrice: 8999, rating: 4.5, description: "Lightweight carbon fiber tripod with ball head, max height 65 inches.", colors: ["Black", "Grey"], sizes: [], inStock: true, images: imgs("CM003", 3) },
  { id: "CM004", name: "Camera Lens 50mm f/1.8", brand: "OpticPro", category: "cameras", price: 8999, originalPrice: 14999, rating: 4.6, description: "Fast prime lens with silent autofocus motor and metal mount.", colors: ["Black"], sizes: [], inStock: true, images: imgs("CM004", 3) },
  { id: "CM005", name: "Camera Backpack", brand: "GearPack", category: "cameras", price: 1999, originalPrice: 3999, rating: 4.3, description: "Waterproof camera backpack with customizable dividers and laptop compartment.", colors: ["Black", "Grey", "Khaki"], sizes: [], inStock: true, images: imgs("CM005", 3) },
  { id: "CM006", name: "Ring Light 18\"", brand: "BrightStudio", category: "cameras", price: 2499, originalPrice: 4999, rating: 4.4, description: "18-inch ring light with tripod stand, phone holder, and adjustable color temperature.", colors: ["Black", "White"], sizes: ["12 inch", "18 inch"], inStock: true, images: imgs("CM006", 3) },
  { id: "CM007", name: "Instant Camera", brand: "SnapQuick", category: "cameras", price: 5999, originalPrice: 9999, rating: 4.5, description: "Instant camera with auto-exposure, built-in flash, and selfie mirror. Film included.", colors: ["White", "Black", "Mint", "Pink"], sizes: [], inStock: true, images: imgs("CM007", 4) },

  // === MOBILE PHONES (7) ===
  { id: "MP001", name: "Flagship Smartphone 256GB", brand: "NovaTech", category: "phones", price: 39999, originalPrice: 59999, rating: 4.7, description: "6.7-inch AMOLED display, Snapdragon 8 Gen 3, 108MP camera, 5000mAh battery.", colors: ["Midnight Black", "Ocean Blue", "Forest Green"], sizes: ["128GB", "256GB", "512GB"], inStock: true, images: imgs("MP001", 4) },
  { id: "MP002", name: "Budget Smartphone 128GB", brand: "ValuePhone", category: "phones", price: 12999, originalPrice: 19999, rating: 4.3, description: "6.5-inch HD+ display, MediaTek Helio G88, 50MP triple camera, 5050mAh battery.", colors: ["Black", "Blue", "Gold"], sizes: ["64GB", "128GB"], inStock: true, images: imgs("MP002", 3) },
  { id: "MP003", name: "Smartphone Case Leather", brand: "CaseCraft", category: "phones", price: 799, originalPrice: 1499, rating: 4.2, description: "Genuine leather phone case with card slots and magnetic closure.", colors: ["Brown", "Black", "Tan"], sizes: ["iPhone 15 Pro", "Samsung S24 Ultra"], inStock: true, images: imgs("MP003", 3) },
  { id: "MP004", name: "Tempered Glass Screen Protector", brand: "GlassShield", category: "phones", price: 299, originalPrice: 599, rating: 4.3, description: "9H hardness tempered glass with oleophobic coating. Pack of 2.", colors: ["Clear"], sizes: ["iPhone 15", "Samsung S24", "OnePlus 12"], inStock: true, images: imgs("MP004", 3) },
  { id: "MP005", name: "Wireless Car Charger Mount", brand: "ChargeDrive", category: "phones", price: 999, originalPrice: 1999, rating: 4.2, description: "15W fast wireless car charger with auto-clamping mount and LED indicator.", colors: ["Black"], sizes: [], inStock: true, images: imgs("MP005", 3) },
  { id: "MP006", name: "Phone Gimbal Stabilizer", brand: "SmoothShot", category: "phones", price: 3499, originalPrice: 6499, rating: 4.4, description: "3-axis phone gimbal with object tracking, motion lapse, and built-in tripod.", colors: ["Black", "White"], sizes: [], inStock: true, images: imgs("MP006", 3) },
  { id: "MP007", name: "SIM Card Adapter Kit", brand: "ConnectAll", category: "phones", price: 199, originalPrice: 399, rating: 4.1, description: "Nano/Micro/Standard SIM card adapter set with SIM ejector tool.", colors: ["White"], sizes: [], inStock: true, images: imgs("MP007", 3) },

  // === LAPTOPS & COMPUTERS (7) ===
  { id: "LC001", name: "Ultrabook 14\" i7", brand: "SwiftBook", category: "computers", price: 59999, originalPrice: 84999, rating: 4.6, description: "14-inch FHD+ display, Intel i7-13700H, 16GB RAM, 512GB SSD, Thunderbolt 4.", colors: ["Silver", "Space Grey"], sizes: ["i5/8GB", "i7/16GB", "i7/32GB"], inStock: true, images: imgs("LC001", 4) },
  { id: "LC002", name: "Gaming Laptop 15.6\"", brand: "TitanGaming", category: "computers", price: 79999, originalPrice: 119999, rating: 4.5, description: "15.6-inch 165Hz display, RTX 4070, Intel i7-13700HX, 16GB RAM, 1TB SSD.", colors: ["Black", "White"], sizes: ["RTX 4060", "RTX 4070"], inStock: true, images: imgs("LC002", 4) },
  { id: "LC003", name: "Desktop PC Ryzen 7", brand: "PowerBuild", category: "computers", price: 54999, originalPrice: 79999, rating: 4.5, description: "Ryzen 7 7700X, RTX 4060, 32GB DDR5, 1TB NVMe SSD, RGB case.", colors: ["Black"], sizes: ["RTX 4060", "RTX 4070"], inStock: true, images: imgs("LC003", 3) },
  { id: "LC004", name: "27\" 4K Monitor", brand: "ClearView", category: "computers", price: 19999, originalPrice: 34999, rating: 4.5, description: "27-inch 4K IPS monitor with 99% sRGB, USB-C input, and adjustable stand.", colors: ["Black", "Silver"], sizes: ["27 inch", "32 inch"], inStock: true, images: imgs("LC004", 3) },
  { id: "LC005", name: "SSD 1TB NVMe", brand: "SpeedDrive", category: "computers", price: 5999, originalPrice: 9999, rating: 4.6, description: "1TB NVMe M.2 SSD with 7000MB/s read speed and DRAM cache.", colors: ["Black"], sizes: ["512GB", "1TB", "2TB"], inStock: true, images: imgs("LC005", 3) },
  { id: "LC006", name: "RAM DDR5 32GB Kit", brand: "HyperMem", category: "computers", price: 6999, originalPrice: 11999, rating: 4.5, description: "32GB (2x16GB) DDR5 6000MHz RAM with RGB heatspreader.", colors: ["Black", "White"], sizes: ["16GB", "32GB", "64GB"], inStock: true, images: imgs("LC006", 3) },
  { id: "LC007", name: "Mini PC Intel N100", brand: "CompactBox", category: "computers", price: 14999, originalPrice: 22999, rating: 4.3, description: "Fanless mini PC with Intel N100, 8GB RAM, 256GB SSD. VESA mountable.", colors: ["Black", "Silver"], sizes: ["8/256GB", "16/512GB"], inStock: true, images: imgs("LC007", 3) },

  // === AUDIO & HEADPHONES (7) ===
  { id: "AD001", name: "Over-Ear Headphones ANC", brand: "SoundElite", category: "audio", price: 4999, originalPrice: 9999, rating: 4.7, description: "Premium over-ear headphones with adaptive ANC, 40hr battery, and Hi-Res audio.", colors: ["Black", "Silver", "Navy"], sizes: [], inStock: true, images: imgs("AD001", 4) },
  { id: "AD002", name: "Wireless Earbuds Sport", brand: "FitSound", category: "audio", price: 1499, originalPrice: 2999, rating: 4.4, description: "Sport wireless earbuds with ear hooks, IPX8 waterproof, and 10hr battery.", colors: ["Black", "Green", "Pink"], sizes: [], inStock: true, images: imgs("AD002", 3) },
  { id: "AD003", name: "Soundbar 2.1 Channel", brand: "CinemaSound", category: "audio", price: 8999, originalPrice: 16999, rating: 4.5, description: "2.1 channel soundbar with wireless subwoofer, Dolby Audio, and HDMI ARC.", colors: ["Black"], sizes: [], inStock: true, images: imgs("AD003", 3) },
  { id: "AD004", name: "Turntable Vinyl Player", brand: "RetroVinyl", category: "audio", price: 5999, originalPrice: 9999, rating: 4.4, description: "Belt-drive turntable with built-in preamp, USB output, and Bluetooth.", colors: ["Walnut", "Black"], sizes: [], inStock: true, images: imgs("AD004", 3) },
  { id: "AD005", name: "Studio Monitor Speakers", brand: "ProAudio", category: "audio", price: 12999, originalPrice: 22999, rating: 4.6, description: "Pair of 5-inch studio monitors with bi-amped design and flat frequency response.", colors: ["Black", "White"], sizes: ["5 inch", "8 inch"], inStock: true, images: imgs("AD005", 3) },
  { id: "AD006", name: "Podcast Microphone USB", brand: "VoiceClear", category: "audio", price: 3999, originalPrice: 6999, rating: 4.5, description: "Condenser USB microphone with headphone monitoring, gain control, and mute button.", colors: ["Black", "Silver"], sizes: [], inStock: true, images: imgs("AD006", 3) },
  { id: "AD007", name: "DAC Amplifier Portable", brand: "AudioFidelity", category: "audio", price: 2499, originalPrice: 4499, rating: 4.4, description: "Hi-Res portable DAC/amp with dual ESS chips, MQA support, and 3.5mm/4.4mm output.", colors: ["Black", "Silver"], sizes: [], inStock: true, images: imgs("AD007", 3) },

  // === FASHION MEN (6) ===
  { id: "MF001", name: "Slim Fit Dress Pants", brand: "GentStyle", category: "mens-fashion", price: 1499, originalPrice: 2999, rating: 4.4, description: "Wool-blend slim fit dress pants with flat front and crease-resistant finish.", colors: ["Charcoal", "Navy", "Black"], sizes: ["28", "30", "32", "34", "36"], inStock: true, images: imgs("MF001", 3) },
  { id: "MF002", name: "Casual Linen Shirt", brand: "BreezeWear", category: "mens-fashion", price: 1199, originalPrice: 2299, rating: 4.3, description: "100% linen casual shirt with relaxed fit, perfect for summer.", colors: ["White", "Blue", "Pink", "Green"], sizes: ["S", "M", "L", "XL"], inStock: true, images: imgs("MF002", 4) },
  { id: "MF003", name: "Leather Belt Reversible", brand: "ClassicBelt", category: "mens-fashion", price: 899, originalPrice: 1799, rating: 4.2, description: "Reversible genuine leather belt - black on one side, brown on the other.", colors: ["Black/Brown"], sizes: ["30", "32", "34", "36", "38"], inStock: true, images: imgs("MF003", 3) },
  { id: "MF004", name: "Crew Neck Sweatshirt", brand: "UrbanChill", category: "mens-fashion", price: 1299, originalPrice: 2499, rating: 4.4, description: "Heavyweight cotton sweatshirt with brushed fleece interior and ribbed trim.", colors: ["Grey", "Black", "Navy", "Maroon"], sizes: ["S", "M", "L", "XL"], inStock: true, images: imgs("MF004", 3) },
  { id: "MF005", name: "Chino Shorts", brand: "SummerFit", category: "mens-fashion", price: 799, originalPrice: 1499, rating: 4.2, description: "9-inch inseam chino shorts with stretch fabric and side pockets.", colors: ["Khaki", "Navy", "Olive", "White"], sizes: ["28", "30", "32", "34"], inStock: true, images: imgs("MF005", 3) },
  { id: "MF006", name: "Bomber Jacket", brand: "StreetEdge", category: "mens-fashion", price: 2499, originalPrice: 4999, rating: 4.5, description: "Satin bomber jacket with ribbed collar, cuffs, and hem. Zip closure.", colors: ["Black", "Navy", "Olive"], sizes: ["S", "M", "L", "XL"], inStock: true, images: imgs("MF006", 4) },

  // === FASHION WOMEN (6) ===
  { id: "WF001", name: "Floral Print Maxi Dress", brand: "BloomStyle", category: "womens-fashion", price: 1799, originalPrice: 3499, rating: 4.5, description: "Flowing floral maxi dress with adjustable straps, smocked waist, and side slit.", colors: ["Blue Floral", "Red Floral", "Green Floral"], sizes: ["XS", "S", "M", "L"], inStock: true, images: imgs("WF001", 4) },
  { id: "WF002", name: "High-Waist Leggings", brand: "FlexFit", category: "womens-fashion", price: 899, originalPrice: 1799, rating: 4.4, description: "Buttery soft high-waist leggings with 4-way stretch and hidden pocket.", colors: ["Black", "Navy", "Grey", "Burgundy"], sizes: ["XS", "S", "M", "L", "XL"], inStock: true, images: imgs("WF002", 3) },
  { id: "WF003", name: "Wrap Blouse", brand: "ElegantTee", category: "womens-fashion", price: 1099, originalPrice: 2199, rating: 4.3, description: "V-neck wrap blouse with tie waist, bell sleeves, and soft fabric.", colors: ["White", "Black", "Blush"], sizes: ["XS", "S", "M", "L"], inStock: true, images: imgs("WF003", 3) },
  { id: "WF004", name: "Pleated Midi Skirt", brand: "GraceStyle", category: "womens-fashion", price: 1299, originalPrice: 2499, rating: 4.4, description: "Flowing pleated midi skirt with elastic waistband and satin finish.", colors: ["Black", "Champagne", "Forest Green"], sizes: ["XS", "S", "M", "L"], inStock: true, images: imgs("WF004", 3) },
  { id: "WF005", name: "Oversized Blazer", brand: "PowerWoman", category: "womens-fashion", price: 2499, originalPrice: 4999, rating: 4.5, description: "Single-breasted oversized blazer with padded shoulders and side pockets.", colors: ["Black", "Cream", "Grey"], sizes: ["XS", "S", "M", "L"], inStock: true, images: imgs("WF005", 4) },
  { id: "WF006", name: "Casual Denim Jacket", brand: "VintageRose", category: "womens-fashion", price: 1999, originalPrice: 3999, rating: 4.4, description: "Classic denim jacket with dropped shoulders and distressed details.", colors: ["Light Blue", "Dark Blue", "Black"], sizes: ["XS", "S", "M", "L"], inStock: true, images: imgs("WF006", 3) }
];

module.exports = productsC;
