const { helper_pick, helper_range } = require('./generate-data.js');

const imgBase = 'https://placehold.co/600x600';
function imgs(id, count) {
  const a = [];
  for (let i = 1; i <= count; i++) a.push(imgBase + '?text=' + encodeURIComponent(id) + '-img' + i);
  return a;
}

const productsD = [
  // === SHOES & FOOTWEAR (6) ===
  { id: "SH001", name: "Running Shoes Air Cushion", brand: "RunMax", category: "shoes", price: 2499, originalPrice: 4999, rating: 4.5, description: "Lightweight running shoes with air cushion sole, breathable mesh upper.", colors: ["Black/White", "Blue/Grey", "Red/Black"], sizes: ["7", "8", "9", "10", "11"], inStock: true, images: imgs("SH001", 4) },
  { id: "SH002", name: "Classic White Sneakers", brand: "UrbanStep", category: "shoes", price: 1999, originalPrice: 3999, rating: 4.4, description: "Minimalist white leather sneakers with rubber sole and cushioned insole.", colors: ["White", "White/Green"], sizes: ["6", "7", "8", "9", "10"], inStock: true, images: imgs("SH002", 3) },
  { id: "SH003", name: "Formal Oxford Shoes", brand: "GentWalk", category: "shoes", price: 3499, originalPrice: 6999, rating: 4.6, description: "Premium leather oxford shoes with Goodyear welt construction.", colors: ["Black", "Brown"], sizes: ["7", "8", "9", "10", "11"], inStock: true, images: imgs("SH003", 3) },
  { id: "SH004", name: "Slides & Slippers", brand: "ComfyWalk", category: "shoes", price: 499, originalPrice: 999, rating: 4.2, description: "Memory foam slides with adjustable strap. Perfect for home or casual wear.", colors: ["Black", "Grey", "Pink", "Blue"], sizes: ["6", "7", "8", "9", "10"], inStock: true, images: imgs("SH004", 3) },
  { id: "SH005", name: "Hiking Boots Waterproof", brand: "TrailBlazer", category: "shoes", price: 4999, originalPrice: 8999, rating: 4.5, description: "Waterproof hiking boots with Vibram sole, ankle support, and Gore-Tex lining.", colors: ["Brown/Black", "Grey/Orange"], sizes: ["7", "8", "9", "10", "11"], inStock: true, images: imgs("SH005", 4) },
  { id: "SH006", name: "Canvas Loafers", brand: "DeckShoe", category: "shoes", price: 1299, originalPrice: 2499, rating: 4.3, description: "Breathable canvas loafers with memory foam insole and flexible sole.", colors: ["Navy", "Khaki", "Grey", "Red"], sizes: ["6", "7", "8", "9", "10"], inStock: true, images: imgs("SH006", 3) },

  // === BAGS & LUGGAGE (6) ===
  { id: "BL001", name: "Travel Backpack 40L", brand: "VoyagePack", category: "bags", price: 2999, originalPrice: 5999, rating: 4.5, description: "40L travel backpack with laptop compartment, USB charging port, and rain cover.", colors: ["Black", "Grey", "Navy"], sizes: ["30L", "40L"], inStock: true, images: imgs("BL001", 4) },
  { id: "BL002", name: "Crossbody Sling Bag", brand: "QuickCarry", category: "bags", price: 799, originalPrice: 1499, rating: 4.3, description: "Compact sling bag with anti-theft back pocket and adjustable strap.", colors: ["Black", "Grey", "Olive"], sizes: [], inStock: true, images: imgs("BL002", 3) },
  { id: "BL003", name: "Hard Shell Trolley 24\"", brand: "SkyRider", category: "bags", price: 5999, originalPrice: 11999, rating: 4.6, description: "Polycarbonate trolley suitcase with TSA lock, silent wheels, and expandable design.", colors: ["Black", "Silver", "Navy", "Rose Gold"], sizes: ["20 inch", "24 inch", "28 inch"], inStock: true, images: imgs("BL003", 4) },
  { id: "BL004", name: "Tote Bag Canvas", brand: "MarketTote", category: "bags", price: 699, originalPrice: 1299, rating: 4.2, description: "Oversized canvas tote bag with zip closure and inner pockets.", colors: ["Natural", "Black", "Navy"], sizes: [], inStock: true, images: imgs("BL004", 3) },
  { id: "BL005", name: "Gym Duffle Bag", brand: "FitPack", category: "bags", price: 1299, originalPrice: 2499, rating: 4.3, description: "Water-resistant gym bag with shoe compartment, wet pocket, and shoulder strap.", colors: ["Black", "Grey", "Blue"], sizes: ["30L", "45L"], inStock: true, images: imgs("BL005", 3) },
  { id: "BL006", name: "Laptop Messenger Bag", brand: "WorkCarry", category: "bags", price: 1499, originalPrice: 2999, rating: 4.4, description: "Professional laptop messenger with padded compartment, fits up to 15.6 inches.", colors: ["Black", "Brown", "Grey"], sizes: [], inStock: true, images: imgs("BL006", 3) },

  // === JEWELLERY (6) ===
  { id: "JW001", name: "Gold-Plated Necklace Set", brand: "LuxeGlow", category: "jewellery", price: 799, originalPrice: 1499, rating: 4.4, description: "Layered gold-plated necklace set with pendant. Tarnish-free, hypoallergenic.", colors: ["Gold", "Rose Gold"], sizes: [], inStock: true, images: imgs("JW001", 3) },
  { id: "JW002", name: "Sterling Silver Ring", brand: "SilverCraft", category: "jewellery", price: 999, originalPrice: 1999, rating: 4.5, description: "925 sterling silver adjustable ring with cubic zirconia stone.", colors: ["Silver", "Gold-Plated"], sizes: ["5", "6", "7", "8"], inStock: true, images: imgs("JW002", 3) },
  { id: "JW003", name: "Pearl Stud Earrings", brand: "PearlPoint", category: "jewellery", price: 699, originalPrice: 1399, rating: 4.6, description: "Freshwater pearl stud earrings with sterling silver posts.", colors: ["White", "Cream"], sizes: ["6mm", "8mm"], inStock: true, images: imgs("JW003", 3) },
  { id: "JW004", name: "Bracelet Charm Set", brand: "CharmHouse", category: "jewellery", price: 599, originalPrice: 1199, rating: 4.3, description: "Set of 3 adjustable charm bracelets with heart, star, and evil eye charms.", colors: ["Gold", "Silver", "Rose Gold"], sizes: [], inStock: true, images: imgs("JW004", 3) },
  { id: "JW005", name: "Anklet Chain", brand: "ShineChain", category: "jewellery", price: 399, originalPrice: 799, rating: 4.2, description: "Dainty anklet chain with adjustable clasp. Waterproof and tarnish-free.", colors: ["Gold", "Silver"], sizes: [], inStock: true, images: imgs("JW005", 3) },
  { id: "JW006", name: "Men's Bracelet Leather", brand: "GentCraft", category: "jewellery", price: 599, originalPrice: 1199, rating: 4.3, description: "Braided leather bracelet with stainless steel magnetic clasp.", colors: ["Brown", "Black"], sizes: [], inStock: true, images: imgs("JW006", 3) },

  // === HOME DECOR (6) ===
  { id: "HD001", name: "Wall Art Canvas Set", brand: "ArtSpace", category: "decor", price: 1499, originalPrice: 2999, rating: 4.4, description: "Set of 3 abstract canvas prints, gallery-wrapped and ready to hang.", colors: ["Multi"], sizes: ["12x16", "16x20", "20x24"], inStock: true, images: imgs("HD001", 4) },
  { id: "HD002", name: "Throw Pillow Covers", brand: "CozyNest", category: "decor", price: 499, originalPrice: 999, rating: 4.3, description: "Set of 4 velvet throw pillow covers with hidden zipper. 18x18 inches.", colors: ["Grey", "Navy", "Blush", "Mustard"], sizes: ["16x16", "18x18", "20x20"], inStock: true, images: imgs("HD002", 3) },
  { id: "HD003", name: "Table Lamp Modern", brand: "LightArt", category: "decor", price: 1999, originalPrice: 3999, rating: 4.5, description: "Modern table lamp with fabric shade, touch dimmer, and USB charging port.", colors: ["White", "Black", "Brass"], sizes: [], inStock: true, images: imgs("HD003", 3) },
  { id: "HD004", name: "Wall Mirror Round", brand: "MirrorGlow", category: "decor", price: 2499, originalPrice: 4999, rating: 4.4, description: "24-inch round wall mirror with gold metal frame. Beveled edge.", colors: ["Gold", "Black", "Silver"], sizes: ["18 inch", "24 inch", "30 inch"], inStock: true, images: imgs("HD004", 3) },
  { id: "HD005", name: "Decorative Vase Set", brand: "EarthCraft", category: "decor", price: 999, originalPrice: 1999, rating: 4.3, description: "Set of 3 ceramic vases in varying heights. Minimalist design.", colors: ["White", "Grey", "Terracotta"], sizes: [], inStock: true, images: imgs("HD005", 3) },
  { id: "HD006", name: "Scented Candle Set", brand: "GlowAroma", category: "decor", price: 699, originalPrice: 1299, rating: 4.5, description: "Set of 3 soy wax candles with lavender, vanilla, and sandalwood scents.", colors: ["White", "Pink", "Grey"], sizes: [], inStock: true, images: imgs("HD006", 3) },

  // === GARDEN & OUTDOOR (6) ===
  { id: "GD001", name: "Plant Pot Set Ceramic", brand: "GreenThumb", category: "garden", price: 799, originalPrice: 1499, rating: 4.3, description: "Set of 3 ceramic plant pots with drainage holes and bamboo saucers.", colors: ["White", "Grey", "Terracotta"], sizes: ["Small", "Medium", "Large"], inStock: true, images: imgs("GD001", 3) },
  { id: "GD002", name: "Garden Tool Set", brand: "GrowEasy", category: "garden", price: 999, originalPrice: 1999, rating: 4.4, description: "7-piece garden tool set with trowel, pruner, weeder, and canvas tote.", colors: ["Green/Black"], sizes: [], inStock: true, images: imgs("GD002", 3) },
  { id: "GD003", name: "Solar Garden Lights", brand: "SunGlow", category: "garden", price: 1299, originalPrice: 2499, rating: 4.2, description: "Set of 10 solar-powered LED stake lights. Auto on/off at dusk/dawn.", colors: ["Warm White", "Cool White"], sizes: [], inStock: true, images: imgs("GD003", 3) },
  { id: "GD004", name: "Hammock with Stand", brand: "RelaxMax", category: "garden", price: 3999, originalPrice: 7499, rating: 4.5, description: "Double hammock with adjustable steel stand, supports up to 200kg.", colors: ["Striped Multi", "Solid Blue"], sizes: [], inStock: true, images: imgs("GD004", 4) },
  { id: "GD005", name: "Herb Garden Kit Indoor", brand: "UrbanFarm", category: "garden", price: 699, originalPrice: 1299, rating: 4.3, description: "Indoor herb garden kit with 6 seed pods, growing medium, and LED grow light.", colors: ["White", "Black"], sizes: [], inStock: true, images: imgs("GD005", 3) },
  { id: "GD006", name: "Watering Can Modern", brand: "AquaGarden", category: "garden", price: 499, originalPrice: 999, rating: 4.2, description: "2-liter stainless steel watering can with long spout and ergonomic handle.", colors: ["Silver", "Black", "Green"], sizes: ["1.5L", "2L"], inStock: true, images: imgs("GD006", 3) },

  // === KITCHEN & DINING (6) ===
  { id: "KD001", name: "Air Fryer Large 6L", brand: "CrispChef", category: "kitchen", price: 4999, originalPrice: 9999, rating: 4.6, description: "6-liter digital air fryer with 8 presets, shake reminder, and non-stick basket.", colors: ["Black", "White"], sizes: ["3.5L", "6L"], inStock: true, images: imgs("KD001", 4) },
  { id: "KD002", name: "Blender High-Speed", brand: "BlendPro", category: "kitchen", price: 3499, originalPrice: 6999, rating: 4.5, description: "1400W high-speed blender with 6 blades, self-cleaning function, and travel cup.", colors: ["Black", "Red"], sizes: [], inStock: true, images: imgs("KD002", 3) },
  { id: "KD003", name: "French Press Coffee Maker", brand: "BrewCraft", category: "kitchen", price: 599, originalPrice: 1199, rating: 4.4, description: "Double-wall insulated French press with 304 stainless steel plunger. Makes 8 cups.", colors: ["Black", "Silver", "Copper"], sizes: ["350ml", "600ml"], inStock: true, images: imgs("KD003", 3) },
  { id: "KD004", name: "Knife Set 8-Piece", brand: "EdgeMaster", category: "kitchen", price: 2999, originalPrice: 5999, rating: 4.5, description: "8-piece knife set with block. High-carbon stainless steel, ergonomic handles.", colors: ["Black", "Silver"], sizes: ["8 Piece"], inStock: true, images: imgs("KD004", 3) },
  { id: "KD005", name: "Instant Pot 6-in-1", brand: "QuickCook", category: "kitchen", price: 5499, originalPrice: 9999, rating: 4.6, description: "6-in-1 electric pressure cooker, slow cooker, rice cooker, steamer, sauté, and warmer.", colors: ["Black", "Red"], sizes: ["3L", "5L", "6L"], inStock: true, images: imgs("KD005", 4) },
  { id: "KD006", name: "Silicone Baking Mat Set", brand: "BakePro", category: "kitchen", price: 399, originalPrice: 799, rating: 4.3, description: "Set of 3 non-stick silicone baking mats. Replaces parchment paper.", colors: ["Grey", "Red"], sizes: [], inStock: true, images: imgs("KD006", 3) },

  // === FITNESS EQUIPMENT (6) ===
  { id: "FE001", name: "Adjustable Dumbbell Set", brand: "PowerLift", category: "fitness", price: 9999, originalPrice: 19999, rating: 4.6, description: "Adjustable dumbbells from 5-50 lbs each with quick-change dial system.", colors: ["Black", "Silver"], sizes: [], inStock: true, images: imgs("FE001", 4) },
  { id: "FE002", name: "Treadmill Foldable", brand: "StepMaster", category: "fitness", price: 24999, originalPrice: 44999, rating: 4.5, description: "Foldable treadmill with 12 programs, Bluetooth speakers, and LCD display.", colors: ["Black", "Grey"], sizes: [], inStock: true, images: imgs("FE002", 3) },
  { id: "FE003", name: "Kettlebell Cast Iron", brand: "IronCore", category: "fitness", price: 1299, originalPrice: 2499, rating: 4.4, description: "Single cast iron kettlebell with vinyl coating and wide handle.", colors: ["Black", "Pink", "Green", "Blue"], sizes: ["4kg", "8kg", "12kg", "16kg"], inStock: true, images: imgs("FE003", 3) },
  { id: "FE004", name: "Exercise Bike Spin", brand: "CycleFit", category: "fitness", price: 14999, originalPrice: 29999, rating: 4.5, description: "Indoor spin bike with magnetic resistance, LCD monitor, and adjustable seat.", colors: ["Black/Red", "All Black"], sizes: [], inStock: true, images: imgs("FE004", 3) },
  { id: "FE005", name: "Pull-Up Bar Doorway", brand: "UpperForce", category: "fitness", price: 999, originalPrice: 1999, rating: 4.3, description: "Multi-grip doorway pull-up bar with foam padding. No screws needed.", colors: ["Black"], sizes: [], inStock: true, images: imgs("FE005", 3) },
  { id: "FE006", name: "Ab Roller Wheel", brand: "CoreCrush", category: "fitness", price: 499, originalPrice: 999, rating: 4.2, description: "Dual-wheel ab roller with knee pad and non-slip grip.", colors: ["Black", "Red"], sizes: [], inStock: true, images: imgs("FE006", 3) },

  // === TRAVEL ESSENTIALS (6) ===
  { id: "TR001", name: "Neck Pillow Memory Foam", brand: "TravelEase", category: "travel", price: 699, originalPrice: 1399, rating: 4.4, description: "Memory foam neck pillow with magnetic clasp, washable cover, and carry bag.", colors: ["Grey", "Blue", "Black"], sizes: [], inStock: true, images: imgs("TR001", 3) },
  { id: "TR002", name: "Packing Cubes Set", brand: "PackSmart", category: "travel", price: 899, originalPrice: 1799, rating: 4.5, description: "Set of 6 packing cubes with compression zippers and ID windows.", colors: ["Grey", "Black", "Blue"], sizes: ["6 Piece"], inStock: true, images: imgs("TR002", 3) },
  { id: "TR003", name: "Travel Adapter Universal", brand: "GlobalPlug", category: "travel", price: 499, originalPrice: 999, rating: 4.3, description: "Universal travel adapter with 3 USB ports. Works in 150+ countries.", colors: ["White", "Black"], sizes: [], inStock: true, images: imgs("TR003", 3) },
  { id: "TR004", name: "Toiletry Bag Hanging", brand: "TravelKit", category: "travel", price: 599, originalPrice: 1199, rating: 4.2, description: "Water-resistant hanging toiletry bag with multiple compartments and mirror.", colors: ["Black", "Grey", "Pink"], sizes: [], inStock: true, images: imgs("TR004", 3) },
  { id: "TR005", name: "Luggage Tag Leather", brand: "TagWise", category: "travel", price: 299, originalPrice: 599, rating: 4.1, description: "Genuine leather luggage tag with privacy cover and steel cable loop.", colors: ["Brown", "Black", "Tan"], sizes: [], inStock: true, images: imgs("TR005", 3) },
  { id: "TR006", name: "Eye Mask Silk", brand: "DreamTravel", category: "travel", price: 399, originalPrice: 799, rating: 4.3, description: "Mulberry silk eye mask with adjustable strap and memory foam padding.", colors: ["Black", "Pink", "Grey"], sizes: [], inStock: true, images: imgs("TR006", 3) },

  // === STATIONERY (6) ===
  { id: "ST001", name: "Fountain Pen Premium", brand: "WriteClass", category: "stationery", price: 1499, originalPrice: 2999, rating: 4.5, description: "Stainless steel fountain pen with fine nib and converter ink system.", colors: ["Black/Gold", "Silver/Blue"], sizes: ["Fine", "Medium"], inStock: true, images: imgs("ST001", 3) },
  { id: "ST002", name: "Gel Pen Set 24 Colors", brand: "ColorWrite", category: "stationery", price: 499, originalPrice: 999, rating: 4.3, description: "Set of 24 gel pens with fine 0.5mm tips. Vibrant, smooth, and quick-drying.", colors: ["Multi"], sizes: [], inStock: true, images: imgs("ST002", 3) },
  { id: "ST003", name: "Washi Tape Collection", brand: "CraftTape", category: "stationery", price: 349, originalPrice: 699, rating: 4.4, description: "Set of 15 washi tapes in various patterns and widths. Great for journaling.", colors: ["Multi"], sizes: ["15mm", "25mm"], inStock: true, images: imgs("ST003", 3) },
  { id: "ST004", name: "Sticky Notes Variety", brand: "NotePop", category: "stationery", price: 249, originalPrice: 499, rating: 4.2, description: "Pack of 500 sticky notes in 12 colors, 4 sizes, and various shapes.", colors: ["Multi"], sizes: [], inStock: true, images: imgs("ST004", 3) },
  { id: "ST005", name: "Desk Calendar 2026", brand: "TimeWrite", category: "stationery", price: 299, originalPrice: 599, rating: 4.1, description: "Easel desk calendar with monthly views, holidays, and motivational quotes.", colors: ["Minimal White", "Floral", "Vintage"], sizes: [], inStock: true, images: imgs("ST005", 3) },
  { id: "ST006", name: "Pencil Case Large", brand: "CarryAll", category: "stationery", price: 399, originalPrice: 799, rating: 4.3, description: "Oversized pencil case with 3 compartments and zipper closure. Fits 50+ pens.", colors: ["Black", "Grey", "Pink", "Blue"], sizes: [], inStock: true, images: imgs("ST006", 3) },

  // === SMART WATCHES (6) ===
  { id: "SW001", name: "Smartwatch Pro GPS", brand: "TimeTech", category: "watches", price: 9999, originalPrice: 17999, rating: 4.6, description: "AMOLED always-on display, GPS, heart rate, SpO2, 14-day battery, 100+ sports modes.", colors: ["Black", "Silver", "Rose Gold"], sizes: ["40mm", "44mm"], inStock: true, images: imgs("SW001", 4) },
  { id: "SW002", name: "Budget Smartwatch", brand: "ValueTime", category: "watches", price: 2999, originalPrice: 5999, rating: 4.3, description: "1.75-inch HD display, Bluetooth calling, heart rate, and 10-day battery.", colors: ["Black", "Silver", "Pink"], sizes: [], inStock: true, images: imgs("SW002", 3) },
  { id: "SW003", name: "Smart Band Fitness", brand: "FitBand", category: "watches", price: 1499, originalPrice: 2999, rating: 4.4, description: "Slim fitness band with color display, sleep tracking, and 14-day battery.", colors: ["Black", "Blue", "Rose", "Green"], sizes: [], inStock: true, images: imgs("SW003", 3) },
  { id: "SW004", name: "Classic Hybrid Watch", brand: "RetroSmart", category: "watches", price: 4999, originalPrice: 8999, rating: 4.5, description: "Hybrid smartwatch with analog hands, hidden display, and fitness tracking.", colors: ["Silver/Black", "Gold/White"], sizes: [], inStock: true, images: imgs("SW004", 3) },
  { id: "SW005", name: "Kids Smartwatch GPS", brand: "SafeKid", category: "watches", price: 3499, originalPrice: 6499, rating: 4.4, description: "GPS tracker watch for kids with SOS button, voice calls, and geo-fencing.", colors: ["Blue", "Pink", "Green"], sizes: [], inStock: true, images: imgs("SW005", 3) },
  { id: "SW006", name: "Watch Band Replacement", brand: "SwapStrap", category: "watches", price: 399, originalPrice: 799, rating: 4.2, description: "Silicone sport watch band compatible with major smartwatches. Quick-release.", colors: ["Black", "White", "Navy", "Red", "Green"], sizes: ["38mm", "42mm", "44mm", "46mm"], inStock: true, images: imgs("SW006", 3) },

  // === BABY FASHION (6) ===
  { id: "BF001", name: "Baby Onesie Set 5-Pack", brand: "TinyTots", category: "kids-fashion", price: 799, originalPrice: 1499, rating: 4.5, description: "Pack of 5 organic cotton onesies with snap closure. Gentle on baby skin.", colors: ["Pastel Mix", "Bold Mix"], sizes: ["0-3m", "3-6m", "6-12m"], inStock: true, images: imgs("BF001", 3) },
  { id: "BF002", name: "Kids Rain Jacket", brand: "WeatherKid", category: "kids-fashion", price: 699, originalPrice: 1299, rating: 4.3, description: "Lightweight waterproof rain jacket with hood and reflective strips.", colors: ["Yellow", "Blue", "Pink"], sizes: ["2-3y", "4-5y", "6-7y", "8-9y"], inStock: true, images: imgs("BF002", 3) },
  { id: "BF003", name: "Toddler Sneakers Soft", brand: "FirstStep", category: "kids-fashion", price: 599, originalPrice: 1199, rating: 4.4, description: "Soft-sole toddler sneakers with velcro closure. Easy to put on and take off.", colors: ["White/Pink", "White/Blue", "All White"], sizes: ["3-6m", "6-12m", "12-18m"], inStock: true, images: imgs("BF003", 3) },
  { id: "BF004", name: "Kids Winter Jacket", brand: "WarmKid", category: "kids-fashion", price: 1299, originalPrice: 2499, rating: 4.5, description: "Padded winter jacket with fleece lining, zip front, and detachable hood.", colors: ["Red", "Blue", "Black"], sizes: ["4-5y", "6-7y", "8-9y", "10-11y"], inStock: true, images: imgs("BF004", 3) },
  { id: "BF005", name: "Baby Booties Knit", brand: "CozyFeet", category: "kids-fashion", price: 299, originalPrice: 599, rating: 4.3, description: "Hand-knitted baby booties with anti-slip sole. 100% cotton.", colors: ["Cream", "Pink", "Blue", "Grey"], sizes: ["0-6m", "6-12m"], inStock: true, images: imgs("BF005", 3) },
  { id: "BF006", name: "Kids Denim Overalls", brand: "LittleDenim", category: "kids-fashion", price: 899, originalPrice: 1799, rating: 4.4, description: "Classic denim overalls with adjustable straps and multiple pockets.", colors: ["Light Blue", "Dark Blue"], sizes: ["2-3y", "4-5y", "6-7y"], inStock: true, images: imgs("BF006", 3) },

  // === FOOD & BEVERAGES (6) ===
  { id: "FB001", name: "Premium Coffee Beans 1kg", brand: "RoastMaster", category: "food-beverages", price: 699, originalPrice: 1299, rating: 4.6, description: "Single-origin Arabica coffee beans, medium roast. Notes of chocolate and caramel.", colors: [], sizes: ["250g", "500g", "1kg"], inStock: true, images: imgs("FB001", 3) },
  { id: "FB002", name: "Matcha Powder Premium", brand: "GreenTea Co.", category: "food-beverages", price: 899, originalPrice: 1699, rating: 4.5, description: "Ceremonial grade matcha powder from Uji, Japan. Stone-ground, vibrant green.", colors: [], sizes: ["30g", "100g"], inStock: true, images: imgs("FB002", 3) },
  { id: "FB003", name: "Protein Bar Pack 12", brand: "FuelBar", category: "food-beverages", price: 1199, originalPrice: 2199, rating: 4.3, description: "Pack of 12 protein bars with 20g protein each. Chocolate peanut butter flavor.", colors: [], sizes: ["6 Pack", "12 Pack"], inStock: true, images: imgs("FB003", 3) },
  { id: "FB004", name: "Herbal Tea Collection", brand: "SteepWell", category: "food-beverages", price: 499, originalPrice: 999, rating: 4.4, description: "Collection of 40 herbal tea bags: chamomile, peppermint, ginger, and hibiscus.", colors: [], sizes: ["20 bags", "40 bags"], inStock: true, images: imgs("FB004", 3) },
  { id: "FB005", name: "Artisan Hot Sauce Set", brand: "HeatCraft", category: "food-beverages", price: 599, originalPrice: 1099, rating: 4.5, description: "Set of 4 artisan hot sauces ranging from mild to extra hot.", colors: [], sizes: [], inStock: true, images: imgs("FB005", 3) },
  { id: "FB006", name: "Energy Drink Variety Pack", brand: "VigorBoost", category: "food-beverages", price: 799, originalPrice: 1499, rating: 4.2, description: "Pack of 12 sugar-free energy drinks in 4 flavors. 160mg caffeine each.", colors: [], sizes: ["6 Pack", "12 Pack"], inStock: true, images: imgs("FB006", 3) },

  // === SPORTS EQUIPMENT (6) ===
  { id: "SE001", name: "Cricket Bat English Willow", brand: "BoundaryKing", category: "sports-equipment", price: 4999, originalPrice: 9999, rating: 4.6, description: "Grade 1 English willow cricket bat with sweet spot and toe guard.", colors: [], sizes: ["Short Handle", "Long Handle"], inStock: true, images: imgs("SE001", 4) },
  { id: "SE002", name: "Basketball Official Size", brand: "HoopStar", category: "sports-equipment", price: 999, originalPrice: 1999, rating: 4.4, description: "Size 7 official basketball with deep channel design and composite leather.", colors: ["Orange", "Black/Gold"], sizes: ["Size 5", "Size 6", "Size 7"], inStock: true, images: imgs("SE002", 3) },
  { id: "SE003", name: "Football Soccer Ball", brand: "GoalPro", category: "sports-equipment", price: 799, originalPrice: 1499, rating: 4.3, description: "FIFA-approved soccer ball with thermal bonding and vivid graphics.", colors: ["Classic White", "Black/White"], sizes: ["Size 4", "Size 5"], inStock: true, images: imgs("SE003", 3) },
  { id: "SE004", name: "Tennis Racket Carbon", brand: "AceStrike", category: "sports-equipment", price: 3999, originalPrice: 7499, rating: 4.5, description: "Carbon fiber tennis racket with 100 sq in head, lightweight frame.", colors: ["Black/Red", "Blue/White"], sizes: ["Grip 2", "Grip 3"], inStock: true, images: imgs("SE004", 3) },
  { id: "SE005", name: "Badminton Racket Set", brand: "SmashPro", category: "sports-equipment", price: 1299, originalPrice: 2499, rating: 4.3, description: "Set of 2 graphite badminton rackets with cover and 6 shuttlecocks.", colors: ["Blue", "Red"], sizes: [], inStock: true, images: imgs("SE005", 3) },
  { id: "SE006", name: "Hockey Stick Composite", brand: "StickMaster", category: "sports-equipment", price: 2499, originalPrice: 4999, rating: 4.4, description: "Composite field hockey stick with control curve and shock absorption.", colors: ["Orange/Black", "Green/White"], sizes: ["36\"", "37\"", "38\""], inStock: true, images: imgs("SE006", 3) },

  // === SMART HOME (6) ===
  { id: "SHO001", name: "Smart Doorbell Camera", brand: "RingSafe", category: "smart-home", price: 4999, originalPrice: 8999, rating: 4.5, description: "Video doorbell with 2K HDR, person detection, two-way audio, and night vision.", colors: ["Black", "Silver"], sizes: [], inStock: true, images: imgs("SHO001", 3) },
  { id: "SHO002", name: "Smart Light Bulb Pack 4", brand: "LumiSmart", category: "smart-home", price: 1499, originalPrice: 2999, rating: 4.4, description: "Pack of 4 RGB smart bulbs with 16 million colors, voice control, and scheduling.", colors: ["White"], sizes: [], inStock: true, images: imgs("SHO002", 3) },
  { id: "SHO003", name: "Robot Mop Cleaner", brand: "SweepSmart", category: "smart-home", price: 12999, originalPrice: 22999, rating: 4.5, description: "Smart robot mop with water tank, mapping, and app scheduling.", colors: ["White", "Black"], sizes: [], inStock: true, images: imgs("SHO003", 3) },
  { id: "SHO004", name: "Smart Thermostat", brand: "TempSmart", category: "smart-home", price: 7999, originalPrice: 14999, rating: 4.6, description: "Learning thermostat with geofencing, energy reports, and voice assistant support.", colors: ["Silver", "Black"], sizes: [], inStock: true, images: imgs("SHO004", 3) },
  { id: "SHO005", name: "Smart Lock Keyless", brand: "LockSecure", category: "smart-home", price: 9999, originalPrice: 17999, rating: 4.5, description: "Keyless deadbolt with fingerprint, PIN, app, and key access. Auto-lock.", colors: ["Black", "Silver"], sizes: [], inStock: true, images: imgs("SHO005", 3) },
  { id: "SHO006", name: "Smart Plug Pack 3", brand: "HomeLink", category: "smart-home", price: 799, originalPrice: 1499, rating: 4.3, description: "Pack of 3 smart plugs with energy monitoring and voice control.", colors: ["White"], sizes: [], inStock: true, images: imgs("SHO006", 3) }
];

module.exports = productsD;
