const { helper_pick, helper_range } = require('./generate-data.js');

const imgBase = 'https://placehold.co/600x600';
function imgs(id, count) {
  const a = [];
  for (let i = 1; i <= count; i++) a.push(imgBase + '?text=' + encodeURIComponent(id) + '-img' + i);
  return a;
}

const productsB = [
  // === ACCESSORIES (8) ===
  { id: "A001", name: "Leather Wallet Bifold", brand: "CraftedStyle", category: "accessories", price: 799, originalPrice: 1499, rating: 4.4, description: "Genuine leather bifold wallet with RFID blocking and 8 card slots.", colors: ["Brown", "Black", "Tan"], sizes: [], inStock: true, images: imgs("A001", 3) },
  { id: "A002", name: "Classic Aviator Sunglasses", brand: "OptiShade", category: "accessories", price: 999, originalPrice: 1999, rating: 4.3, description: "Polarized aviator sunglasses with UV400 protection and metal frame.", colors: ["Gold/Green", "Silver/Blue", "Black/Grey"], sizes: [], inStock: true, images: imgs("A002", 4) },
  { id: "A003", name: "Canvas Belt", brand: "CasualEdge", category: "accessories", price: 399, originalPrice: 799, rating: 4.1, description: "Adjustable canvas belt with brushed metal buckle. Goes with everything.", colors: ["Khaki", "Navy", "Olive", "Black"], sizes: ["S", "M", "L", "XL"], inStock: true, images: imgs("A003", 3) },
  { id: "A004", name: "Knit Beanie", brand: "WarmThread", category: "accessories", price: 299, originalPrice: 599, rating: 4.2, description: "Soft knitted beanie with fleece lining. One size fits all.", colors: ["Black", "Grey", "Red", "Navy"], sizes: [], inStock: true, images: imgs("A004", 3) },
  { id: "A005", name: "Stainless Steel Cufflinks", brand: "FormalEdge", category: "accessories", price: 699, originalPrice: 1399, rating: 4.3, description: "Elegant cufflinks with swivel back closure. Comes in a gift box.", colors: ["Silver", "Gold"], sizes: [], inStock: true, images: imgs("A005", 3) },
  { id: "A006", name: "Phone Case Clear", brand: "ShieldTech", category: "accessories", price: 349, originalPrice: 699, rating: 4.2, description: "Crystal clear protective case with raised edges and air cushion corners.", colors: ["Clear", "Pink Tint", "Blue Tint"], sizes: ["iPhone 15", "Samsung S24", "OnePlus 12"], inStock: true, images: imgs("A006", 3) },
  { id: "A007", name: "Laptop Sleeve 15.6\"", brand: "TechCarry", category: "accessories", price: 599, originalPrice: 1199, rating: 4.3, description: "Water-resistant laptop sleeve with plush interior and front pocket.", colors: ["Black", "Grey", "Navy"], sizes: ["13 inch", "15.6 inch"], inStock: true, images: imgs("A007", 3) },
  { id: "A008", name: "Hair Clip Set", brand: "GlamAccess", category: "accessories", price: 249, originalPrice: 499, rating: 4.0, description: "Set of 10 minimalist hair clips and pins in gold and silver tones.", colors: ["Gold", "Silver", "Mixed"], sizes: [], inStock: true, images: imgs("A008", 3) },

  // === BEAUTY (8) ===
  { id: "BT001", name: "Vitamin C Face Serum", brand: "GlowLab", category: "beauty", price: 599, originalPrice: 1199, rating: 4.5, description: "Brightening face serum with 20% Vitamin C, hyaluronic acid, and vitamin E.", colors: [], sizes: ["30ml", "50ml"], inStock: true, images: imgs("BT001", 3) },
  { id: "BT002", name: "Matte Lipstick Set", brand: "ColorPop", category: "beauty", price: 799, originalPrice: 1499, rating: 4.4, description: "Set of 6 long-lasting matte lipsticks in trending shades. Transfer-proof formula.", colors: ["Nude Set", "Bold Set", "Berry Set"], sizes: [], inStock: true, images: imgs("BT002", 4) },
  { id: "BT003", name: "Hair Dryer Professional", brand: "BlowPro", category: "beauty", price: 2499, originalPrice: 4999, rating: 4.5, description: "2200W professional hair dryer with ionic technology, 3 heat settings, and concentrator nozzle.", colors: ["Black", "Pink"], sizes: [], inStock: true, images: imgs("BT003", 3) },
  { id: "BT004", name: "Sunscreen SPF 50+", brand: "SunShield", category: "beauty", price: 349, originalPrice: 699, rating: 4.6, description: "Lightweight, non-greasy sunscreen with broad spectrum SPF 50+ protection.", colors: [], sizes: ["50ml", "100ml"], inStock: true, images: imgs("BT004", 3) },
  { id: "BT005", name: "Makeup Brush Set", brand: "Artisan Beauty", category: "beauty", price: 999, originalPrice: 1999, rating: 4.3, description: "Set of 12 professional makeup brushes with synthetic bristles and travel pouch.", colors: ["Rose Gold", "Black", "Gold"], sizes: ["12 Piece"], inStock: true, images: imgs("BT005", 3) },
  { id: "BT006", name: "Retinol Night Cream", brand: "GlowLab", category: "beauty", price: 899, originalPrice: 1799, rating: 4.4, description: "Anti-aging night cream with retinol, peptides, and ceramides for smooth skin.", colors: [], sizes: ["30ml", "50ml"], inStock: true, images: imgs("BT006", 3) },
  { id: "BT007", name: "Perfume - Floral Mist", brand: "Essence", category: "beauty", price: 1499, originalPrice: 2999, rating: 4.5, description: "Long-lasting floral fragrance with notes of jasmine, rose, and sandalwood.", colors: [], sizes: ["30ml", "50ml", "100ml"], inStock: true, images: imgs("BT007", 4) },
  { id: "BT008", name: "Micellar Water Cleanser", brand: "PureSkin", category: "beauty", price: 299, originalPrice: 599, rating: 4.3, description: "Gentle micellar water that removes makeup and impurities without rinsing.", colors: [], sizes: ["100ml", "250ml", "500ml"], inStock: true, images: imgs("BT008", 3) },

  // === GROCERY (8) ===
  { id: "G001", name: "Organic Green Tea Box", brand: "NatureLeaf", category: "grocery", price: 199, originalPrice: 399, rating: 4.4, description: "Box of 25 organic green tea bags. Rich in antioxidants, zero calories.", colors: [], sizes: ["25 bags", "50 bags"], inStock: true, images: imgs("G001", 3) },
  { id: "G002", name: "Extra Virgin Olive Oil", brand: "MediterraneanGold", category: "grocery", price: 449, originalPrice: 899, rating: 4.5, description: "Cold-pressed extra virgin olive oil from Italian olives. 750ml bottle.", colors: [], sizes: ["500ml", "750ml", "1L"], inStock: true, images: imgs("G002", 3) },
  { id: "G003", name: "Almond Butter Organic", brand: "NutriBlend", category: "grocery", price: 349, originalPrice: 699, rating: 4.3, description: "Smooth organic almond butter with no added sugar, salt, or oil.", colors: [], sizes: ["200g", "400g"], inStock: true, images: imgs("G003", 3) },
  { id: "G004", name: "Quinoa Superfood Pack", brand: "HealthyGrain", category: "grocery", price: 299, originalPrice: 599, rating: 4.4, description: "Organic white quinoa, pre-rinsed and ready to cook. High protein, gluten-free.", colors: [], sizes: ["500g", "1kg"], inStock: true, images: imgs("G004", 3) },
  { id: "G005", name: "Dark Chocolate 85%", brand: "CocoaCraft", category: "grocery", price: 179, originalPrice: 349, rating: 4.6, description: "Premium dark chocolate bar with 85% cocoa content. Rich, intense flavor.", colors: [], sizes: ["100g", "200g"], inStock: true, images: imgs("G005", 3) },
  { id: "G006", name: "Honey Raw Organic", brand: "BeeNatura", category: "grocery", price: 399, originalPrice: 749, rating: 4.5, description: "Raw, unfiltered organic honey. Never heated, retains all natural enzymes.", colors: [], sizes: ["250g", "500g"], inStock: true, images: imgs("G006", 3) },
  { id: "G007", name: "Protein Granola", brand: "MorningFuel", category: "grocery", price: 349, originalPrice: 649, rating: 4.3, description: "Crunchy granola with 15g protein per serving, oats, nuts, and dried fruits.", colors: [], sizes: ["400g", "800g"], inStock: true, images: imgs("G007", 3) },
  { id: "G008", name: "Coconut Oil Cold-Pressed", brand: "TropicalPure", category: "grocery", price: 299, originalPrice: 549, rating: 4.4, description: "Virgin cold-pressed coconut oil. Multi-use for cooking, baking, and skincare.", colors: [], sizes: ["200ml", "500ml"], inStock: true, images: imgs("G008", 3) },

  // === TOYS & GAMES (8) ===
  { id: "T001", name: "Building Blocks 500pc", brand: "BlockMaster", category: "toys", price: 1299, originalPrice: 2499, rating: 4.6, description: "500-piece building block set with wheels, windows, and instruction booklet.", colors: ["Multi"], sizes: ["250pc", "500pc"], inStock: true, images: imgs("T001", 4) },
  { id: "T002", name: "Remote Control Car", brand: "SpeedToy", category: "toys", price: 1499, originalPrice: 2999, rating: 4.4, description: "High-speed RC car with rechargeable battery, 30km/h top speed.", colors: ["Red", "Blue", "Green"], sizes: [], inStock: true, images: imgs("T002", 3) },
  { id: "T003", name: "Puzzle 1000 Pieces", brand: "BrainTeaser", category: "toys", price: 599, originalPrice: 1099, rating: 4.3, description: "1000-piece jigsaw puzzle featuring world landmarks. Precision-cut pieces.", colors: [], sizes: ["500pc", "1000pc"], inStock: true, images: imgs("T003", 3) },
  { id: "T004", name: "Board Game Classic", brand: "GameNight", category: "toys", price: 799, originalPrice: 1499, rating: 4.5, description: "Strategy board game for 2-6 players. Includes game board, cards, and pieces.", colors: [], sizes: [], inStock: true, images: imgs("T004", 3) },
  { id: "T005", name: "Plush Teddy Bear", brand: "CuddleBuddy", category: "toys", price: 499, originalPrice: 999, rating: 4.7, description: "Super soft plush teddy bear, 12 inches tall, hypoallergenic filling.", colors: ["Brown", "Cream", "Pink"], sizes: ["Small", "Medium", "Large"], inStock: true, images: imgs("T005", 4) },
  { id: "T006", name: "STEM Science Kit", brand: "SmartKids", category: "toys", price: 899, originalPrice: 1699, rating: 4.5, description: "20+ experiments kit with tools, chemicals, and guidebook. Ages 8+.", colors: [], sizes: [], inStock: true, images: imgs("T006", 3) },
  { id: "T007", name: "Nerf Blaster Elite", brand: "NerfZone", category: "toys", price: 1299, originalPrice: 2299, rating: 4.4, description: "Motorized Nerf blaster with 12-dart clip and 24 elite darts.", colors: ["Orange/Blue", "Green/Black"], sizes: [], inStock: true, images: imgs("T007", 3) },
  { id: "T008", name: "Card Game Expansion", brand: "DeckBuilders", category: "toys", price: 399, originalPrice: 799, rating: 4.3, description: "100-card expansion pack with new characters, spells, and strategies.", colors: [], sizes: [], inStock: true, images: imgs("T008", 3) },

  // === BABY PRODUCTS (8) ===
  { id: "BP001", name: "Baby Stroller Lightweight", brand: "LittleJoy", category: "baby", price: 4999, originalPrice: 9999, rating: 4.5, description: "Compact foldable stroller with sun canopy, 5-point harness, and storage basket.", colors: ["Black", "Grey", "Navy"], sizes: [], inStock: true, images: imgs("BP001", 4) },
  { id: "BP002", name: "Diaper Pack Premium", brand: "DryBaby", category: "baby", price: 799, originalPrice: 1299, rating: 4.4, description: "Pack of 40 ultra-absorbent diapers with wetness indicator. Size 4.", colors: [], sizes: ["S", "M", "L", "XL"], inStock: true, images: imgs("BP002", 3) },
  { id: "BP003", name: "Baby Monitor WiFi", brand: "WatchfulEye", category: "baby", price: 3999, originalPrice: 6999, rating: 4.6, description: "HD baby monitor with night vision, two-way audio, lullabies, and app alerts.", colors: ["White"], sizes: [], inStock: true, images: imgs("BP003", 3) },
  { id: "BP004", name: "Bottle Warmer", brand: "FeedEasy", category: "baby", price: 1499, originalPrice: 2999, rating: 4.3, description: "Fast bottle warmer with temperature display, auto shut-off, and sterilizer function.", colors: ["White", "Mint"], sizes: [], inStock: true, images: imgs("BP004", 3) },
  { id: "BP005", name: "Baby Swaddle Blanket", brand: "CozyNest", category: "baby", price: 499, originalPrice: 999, rating: 4.5, description: "Muslin swaddle blanket, 100% cotton, breathable and gentle on skin.", colors: ["Pastel Blue", "Pastel Pink", "Grey", "White"], sizes: [], inStock: true, images: imgs("BP005", 3) },
  { id: "BP006", name: "High Chair Foldable", brand: "MealTime", category: "baby", price: 3499, originalPrice: 6499, rating: 4.4, description: "Adjustable high chair with removable tray, 5-point harness, and easy-clean surface.", colors: ["White", "Grey"], sizes: [], inStock: true, images: imgs("BP006", 3) },
  { id: "BP007", name: "Baby Bath Tub", brand: "SplashTime", category: "baby", price: 999, originalPrice: 1999, rating: 4.3, description: "Non-slip baby bath tub with temperature indicator and plug for easy draining.", colors: ["Blue", "Pink", "White"], sizes: [], inStock: true, images: imgs("BP007", 3) },
  { id: "BP008", name: "Pacifier Set", brand: "CalmBabe", category: "baby", price: 299, originalPrice: 549, rating: 4.2, description: "Set of 3 orthodontic pacifiers with BPA-free silicone. 0-6 months.", colors: ["Blue", "Pink", "Clear"], sizes: ["0-6m", "6-12m"], inStock: true, images: imgs("BP008", 3) },

  // === PET SUPPLIES (8) ===
  { id: "PS001", name: "Dog Food Premium 10kg", brand: "PetNutrition", category: "pets", price: 2499, originalPrice: 4499, rating: 4.5, description: "Premium dry dog food with real chicken, vegetables, and essential nutrients.", colors: [], sizes: ["2kg", "5kg", "10kg"], inStock: true, images: imgs("PS001", 3) },
  { id: "PS002", name: "Cat Litter Box", brand: "CleanPaws", category: "pets", price: 999, originalPrice: 1999, rating: 4.3, description: "Self-cleaning cat litter box with odor control and replaceable carbon filter.", colors: ["Grey", "White"], sizes: [], inStock: true, images: imgs("PS002", 3) },
  { id: "PS003", name: "Pet Bed Orthopedic", brand: "CozyPaws", category: "pets", price: 1499, originalPrice: 2999, rating: 4.6, description: "Memory foam pet bed with waterproof liner and machine-washable cover.", colors: ["Grey", "Brown", "Black"], sizes: ["Small", "Medium", "Large"], inStock: true, images: imgs("PS003", 4) },
  { id: "PS004", name: "Dog Leash Retractable", brand: "WalkEasy", category: "pets", price: 699, originalPrice: 1299, rating: 4.2, description: "16ft retractable dog leash with one-button brake and anti-slip handle.", colors: ["Black", "Blue", "Red"], sizes: ["Small", "Medium", "Large"], inStock: true, images: imgs("PS004", 3) },
  { id: "PS005", name: "Cat Scratching Post", brand: "ScratchWell", category: "pets", price: 899, originalPrice: 1699, rating: 4.4, description: "32-inch cat scratching post with sisal rope, dangling toy, and sturdy base.", colors: ["Beige", "Grey"], sizes: [], inStock: true, images: imgs("PS005", 3) },
  { id: "PS006", name: "Aquarium Filter", brand: "AquaClear", category: "pets", price: 1299, originalPrice: 2499, rating: 4.3, description: "Hang-on-back aquarium filter for tanks up to 50 gallons. Quiet operation.", colors: [], sizes: ["20 gal", "50 gal", "100 gal"], inStock: true, images: imgs("PS006", 3) },
  { id: "PS007", name: "Pet Carrier Airline", brand: "TravelPet", category: "pets", price: 1999, originalPrice: 3999, rating: 4.4, description: "Airline-approved soft pet carrier with ventilation panels and shoulder strap.", colors: ["Grey", "Blue", "Black"], sizes: ["S", "M"], inStock: true, images: imgs("PS007", 3) },
  { id: "PS008", name: "Dog Treats Natural", brand: "GoodBoy", category: "pets", price: 349, originalPrice: 649, rating: 4.5, description: "All-natural dog treats with real beef. No artificial flavors or preservatives.", colors: [], sizes: ["200g", "500g"], inStock: true, images: imgs("PS008", 3) },

  // === HEALTH & WELLNESS (8) ===
  { id: "HW001", name: "Multivitamin Daily", brand: "VitaBoost", category: "health", price: 499, originalPrice: 999, rating: 4.4, description: "Complete daily multivitamin with 25 essential vitamins and minerals. 60 tablets.", colors: [], sizes: ["30 tablets", "60 tablets"], inStock: true, images: imgs("HW001", 3) },
  { id: "HW002", name: "Digital Blood Pressure Monitor", brand: "HealthFirst", category: "health", price: 1999, originalPrice: 3999, rating: 4.5, description: "Automatic blood pressure monitor with large display, memory for 2 users, and irregular heartbeat detection.", colors: ["White", "Grey"], sizes: [], inStock: true, images: imgs("HW002", 3) },
  { id: "HW003", name: "Protein Powder Whey", brand: "FitFuel", category: "health", price: 1999, originalPrice: 3499, rating: 4.6, description: "Whey protein isolate, 27g protein per serving. Low carb, gluten-free. Chocolate flavor.", colors: [], sizes: ["1kg", "2kg"], inStock: true, images: imgs("HW003", 4) },
  { id: "HW004", name: "Omega-3 Fish Oil", brand: "OceanHealth", category: "health", price: 599, originalPrice: 1099, rating: 4.3, description: "Molecularly distilled fish oil with EPA & DHA. 120 softgels.", colors: [], sizes: ["60 caps", "120 caps"], inStock: true, images: imgs("HW004", 3) },
  { id: "HW005", name: "Electric Toothbrush", brand: "SmileBright", category: "health", price: 1299, originalPrice: 2499, rating: 4.5, description: "Sonic electric toothbrush with 5 modes, pressure sensor, and 4 brush heads.", colors: ["White", "Black", "Pink"], sizes: [], inStock: true, images: imgs("HW005", 3) },
  { id: "HW006", name: "Infrared Thermometer", brand: "TempCheck", category: "health", price: 899, originalPrice: 1699, rating: 4.4, description: "Non-contact infrared thermometer with instant readings and fever alarm.", colors: ["White", "Blue"], sizes: [], inStock: true, images: imgs("HW006", 3) },
  { id: "HW007", name: "Sleep Aid Melatonin", brand: "DreamWell", category: "health", price: 349, originalPrice: 699, rating: 4.3, description: "Natural melatonin gummies with chamomile and L-theanine. 60 gummies.", colors: [], sizes: ["30 gummies", "60 gummies"], inStock: true, images: imgs("HW007", 3) },
  { id: "HW008", name: "Posture Corrector", brand: "AlignPro", category: "health", price: 699, originalPrice: 1399, rating: 4.2, description: "Adjustable back posture corrector brace. Comfortable for all-day wear.", colors: ["Black", "Beige"], sizes: ["S/M", "L/XL"], inStock: true, images: imgs("HW008", 3) },

  // === AUTOMOTIVE (7) ===
  { id: "AU001", name: "Car Vacuum Cleaner", brand: "AutoClean", category: "automotive", price: 1499, originalPrice: 2999, rating: 4.3, description: "12V handheld car vacuum with HEPA filter, crevice tool, and 16ft power cord.", colors: ["Black", "Grey"], sizes: [], inStock: true, images: imgs("AU001", 3) },
  { id: "AU002", name: "Dash Cam 4K", brand: "RoadWatch", category: "automotive", price: 3999, originalPrice: 7499, rating: 4.5, description: "4K front and rear dash cam with night vision, GPS, and parking mode.", colors: ["Black"], sizes: [], inStock: true, images: imgs("AU002", 3) },
  { id: "AU003", name: "Car Phone Mount", brand: "DriveSafe", category: "automotive", price: 499, originalPrice: 999, rating: 4.2, description: "Magnetic car phone mount with one-hand operation and 360-degree rotation.", colors: ["Black", "Grey"], sizes: [], inStock: true, images: imgs("AU003", 3) },
  { id: "AU004", name: "Car Air Purifier", brand: "FreshDrive", category: "automotive", price: 1999, originalPrice: 3999, rating: 4.4, description: "HEPA car air purifier with ionizer, USB charging, and whisper-quiet fan.", colors: ["Black", "Silver"], sizes: [], inStock: true, images: imgs("AU004", 3) },
  { id: "AU005", name: "Tire Pressure Gauge", brand: "AutoCheck", category: "automotive", price: 399, originalPrice: 799, rating: 4.1, description: "Digital tire pressure gauge with backlit LCD and LED flashlight.", colors: ["Black"], sizes: [], inStock: true, images: imgs("AU005", 3) },
  { id: "AU006", name: "Seat Cover Set", brand: "AutoComfort", category: "automotive", price: 2499, originalPrice: 4999, rating: 4.3, description: "Full set of leatherette seat covers with memory foam padding. Universal fit.", colors: ["Black", "Tan", "Red/Black"], sizes: [], inStock: true, images: imgs("AU006", 4) },
  { id: "AU007", name: "Car Trunk Organizer", brand: "AutoTidy", category: "automotive", price: 999, originalPrice: 1999, rating: 4.2, description: "Collapsible trunk organizer with insulated compartment and non-slip base.", colors: ["Black", "Grey"], sizes: [], inStock: true, images: imgs("AU007", 3) },

  // === OFFICE SUPPLIES (7) ===
  { id: "OS001", name: "Ergonomic Office Chair", brand: "ComfortSeating", category: "office", price: 8999, originalPrice: 16999, rating: 4.6, description: "Ergonomic mesh office chair with lumbar support, adjustable armrests, and headrest.", colors: ["Black", "Grey"], sizes: [], inStock: true, images: imgs("OS001", 4) },
  { id: "OS002", name: "Desk Organizer Set", brand: "NeatWorkspace", category: "office", price: 799, originalPrice: 1499, rating: 4.3, description: "Bamboo desk organizer with phone stand, pen holder, and drawer.", colors: ["Natural", "White"], sizes: [], inStock: true, images: imgs("OS002", 3) },
  { id: "OS003", name: "Standing Desk Converter", brand: "FlexDesk", category: "office", price: 6999, originalPrice: 12999, rating: 4.5, description: "Height-adjustable standing desk converter with keyboard tray. Fits dual monitors.", colors: ["Black", "White"], sizes: ["32 inch", "36 inch"], inStock: true, images: imgs("OS003", 3) },
  { id: "OS004", name: "Whiteboard Magnetic 60x90", brand: "WriteRight", category: "office", price: 1299, originalPrice: 2499, rating: 4.2, description: "Magnetic dry-erase whiteboard with aluminum frame and marker tray.", colors: ["White"], sizes: ["45x60cm", "60x90cm", "90x120cm"], inStock: true, images: imgs("OS004", 3) },
  { id: "OS005", name: "Paper Shredder", brand: "ShredMaster", category: "office", price: 3499, originalPrice: 6499, rating: 4.4, description: "Cross-cut shredder for 10 sheets at once. Runs 20 minutes continuously.", colors: ["Black", "Grey"], sizes: [], inStock: true, images: imgs("OS005", 3) },
  { id: "OS006", name: "Notebook Set Premium", brand: "PaperTrail", category: "office", price: 599, originalPrice: 1099, rating: 4.3, description: "Set of 3 premium A5 notebooks with dotted, ruled, and blank pages.", colors: ["Black", "Blue", "Green"], sizes: ["A5", "A4"], inStock: true, images: imgs("OS006", 3) },
  { id: "OS007", name: "Wireless Keyboard Mouse", brand: "TechInput", category: "office", price: 1499, originalPrice: 2999, rating: 4.4, description: "Ergonomic wireless keyboard and mouse combo with silent keys and 2.4GHz connection.", colors: ["Black", "White", "Grey"], sizes: [], inStock: true, images: imgs("OS007", 3) },

  // === MUSICAL INSTRUMENTS (7) ===
  { id: "MI001", name: "Acoustic Guitar Starter", brand: "MelodyMaker", category: "music", price: 3499, originalPrice: 6499, rating: 4.4, description: "Full-size dreadnought acoustic guitar with solid spruce top, mahogany back.", colors: ["Natural", "Sunburst"], sizes: ["3/4", "Full"], inStock: true, images: imgs("MI001", 4) },
  { id: "MI002", name: "Electric Keyboard 61-Key", brand: "KeyNote", category: "music", price: 4999, originalPrice: 9999, rating: 4.5, description: "61-key portable keyboard with 400 tones, 150 rhythms, and built-in speakers.", colors: ["Black", "White"], sizes: ["61 key", "88 key"], inStock: true, images: imgs("MI002", 3) },
  { id: "MI003", name: "Ukulele Concert", brand: "IslandTone", category: "music", price: 1299, originalPrice: 2499, rating: 4.3, description: "Concert ukulele with mahogany body, aquila strings, and geared tuners.", colors: ["Natural", "Sunburst"], sizes: ["Soprano", "Concert", "Tenor"], inStock: true, images: imgs("MI003", 3) },
  { id: "MI004", name: "Drum Pad Practice", brand: "BeatMaster", category: "music", price: 999, originalPrice: 1999, rating: 4.2, description: "Double-sided drum practice pad with adjustable mount and carrying bag.", colors: ["Grey", "Black"], sizes: [], inStock: true, images: imgs("MI004", 3) },
  { id: "MI005", name: "Violin 4/4 Full Size", brand: "StringCraft", category: "music", price: 5999, originalPrice: 11999, rating: 4.6, description: "Handcrafted full-size violin with solid maple body, ebony fingerboard, and case.", colors: ["Natural"], sizes: ["1/2", "3/4", "4/4"], inStock: true, images: imgs("MI005", 3) },
  { id: "MI006", name: "Harmonica Blues Set", brand: "BlowBand", category: "music", price: 699, originalPrice: 1299, rating: 4.3, description: "Set of 3 blues harmonicas in keys of C, G, and A. Brass reeds.", colors: ["Silver"], sizes: ["C", "G", "A"], inStock: true, images: imgs("MI006", 3) },
  { id: "MI007", name: "Guitar Amplifier 20W", brand: "ToneBox", category: "music", price: 4499, originalPrice: 7999, rating: 4.4, description: "20W guitar amplifier with overdrive, reverb, and headphone jack.", colors: ["Black"], sizes: ["10W", "20W"], inStock: true, images: imgs("MI007", 3) }
];

module.exports = productsB;
